// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

/**
 * Protobuf type {@code LoginResponse}
 */
public  final class LoginResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LoginResponse)
    LoginResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoginResponse.newBuilder() to construct.
  private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
  private LoginResponse() {
    status_ = "";
    token_ = "";
=======
  private CreateUserResponse() {
    email_ = "";
    password_ = "";
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoginResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
            status_ = s;
=======
            email_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
            token_ = s;
=======
            password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.service.grpc.User.internal_static_LoginResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.service.grpc.User.internal_static_LoginResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.service.grpc.LoginResponse.class, web.service.grpc.LoginResponse.Builder.class);
  }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
  public static final int STATUS_FIELD_NUMBER = 1;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 1;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
=======
  public static final int EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 1;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      status_ = s;
=======
      email_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      return s;
    }
  }
  /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
   * <code>string status = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
=======
   * <code>string email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      status_ = b;
=======
      email_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object token_;
  /**
   * <code>string token = 2;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
=======
  public static final int PASSWORD_FIELD_NUMBER = 2;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 2;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      token_ = s;
=======
      password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      return s;
    }
  }
  /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
   * <code>string token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
=======
   * <code>string password = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      token_ = b;
=======
      password_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
=======
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
=======
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.service.grpc.LoginResponse)) {
      return super.equals(obj);
    }
    web.service.grpc.LoginResponse other = (web.service.grpc.LoginResponse) obj;

    boolean result = true;
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && getToken()
        .equals(other.getToken());
=======
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && getPassword()
        .equals(other.getPassword());
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
=======
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.service.grpc.LoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.LoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.LoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.LoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.service.grpc.LoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.service.grpc.LoginResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LoginResponse)
      web.service.grpc.LoginResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.grpc.User.internal_static_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.grpc.User.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.grpc.LoginResponse.class, web.service.grpc.LoginResponse.Builder.class);
    }

    // Construct using web.service.grpc.LoginResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      status_ = "";

      token_ = "";
=======
      email_ = "";

      password_ = "";
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.service.grpc.User.internal_static_LoginResponse_descriptor;
    }

    public web.service.grpc.LoginResponse getDefaultInstanceForType() {
      return web.service.grpc.LoginResponse.getDefaultInstance();
    }

    public web.service.grpc.LoginResponse build() {
      web.service.grpc.LoginResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    public web.service.grpc.LoginResponse buildPartial() {
      web.service.grpc.LoginResponse result = new web.service.grpc.LoginResponse(this);
      result.status_ = status_;
      result.token_ = token_;
=======
    public web.service.grpc.CreateUserResponse buildPartial() {
      web.service.grpc.CreateUserResponse result = new web.service.grpc.CreateUserResponse(this);
      result.email_ = email_;
      result.password_ = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.service.grpc.LoginResponse) {
        return mergeFrom((web.service.grpc.LoginResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    public Builder mergeFrom(web.service.grpc.LoginResponse other) {
      if (other == web.service.grpc.LoginResponse.getDefaultInstance()) return this;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
=======
    public Builder mergeFrom(web.service.grpc.CreateUserResponse other) {
      if (other == web.service.grpc.CreateUserResponse.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.service.grpc.LoginResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.service.grpc.LoginResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    private java.lang.Object status_ = "";
    /**
     * <code>string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
=======
    private java.lang.Object email_ = "";
    /**
     * <code>string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
        status_ = s;
=======
        email_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
=======
     * <code>string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
        status_ = b;
=======
        email_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string status = 1;</code>
     */
    public Builder setStatus(
=======
     * <code>string email = 1;</code>
     */
    public Builder setEmail(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      status_ = value;
=======
      email_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
=======
     * <code>string email = 1;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string status = 1;</code>
     */
    public Builder setStatusBytes(
=======
     * <code>string email = 1;</code>
     */
    public Builder setEmailBytes(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      status_ = value;
=======
      email_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
    private java.lang.Object token_ = "";
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
=======
    private java.lang.Object password_ = "";
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
        token_ = s;
=======
        password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
=======
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
        token_ = b;
=======
        password_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string token = 2;</code>
     */
    public Builder setToken(
=======
     * <code>string password = 2;</code>
     */
    public Builder setPassword(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      token_ = value;
=======
      password_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
=======
     * <code>string password = 2;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
     * <code>string token = 2;</code>
     */
    public Builder setTokenBytes(
=======
     * <code>string password = 2;</code>
     */
    public Builder setPasswordBytes(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
<<<<<<< HEAD:src/main/java/web/service/grpc/LoginResponse.java
      token_ = value;
=======
      password_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserResponse.java
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LoginResponse)
  }

  // @@protoc_insertion_point(class_scope:LoginResponse)
  private static final web.service.grpc.LoginResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.service.grpc.LoginResponse();
  }

  public static web.service.grpc.LoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginResponse>
      PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
    public LoginResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoginResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginResponse> getParserForType() {
    return PARSER;
  }

  public web.service.grpc.LoginResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

