// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

/**
 * Protobuf type {@code RegistrationInformationRequest}
 */
public  final class RegistrationInformationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RegistrationInformationRequest)
    RegistrationInformationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegistrationInformationRequest.newBuilder() to construct.
  private RegistrationInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
  private RegistrationInformationRequest() {
    email_ = "";
    userName_ = "";
    phone_ = "";
=======
  private CreateUserRequest() {
    email_ = "";
    password_ = "";
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegistrationInformationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
=======
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
            phone_ = s;
=======
            password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.service.grpc.User.internal_static_RegistrationInformationRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.service.grpc.User.internal_static_RegistrationInformationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.service.grpc.RegistrationInformationRequest.class, web.service.grpc.RegistrationInformationRequest.Builder.class);
  }

  public static final int EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 1;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 2;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 3;
  private volatile java.lang.Object phone_;
  /**
   * <code>string phone = 3;</code>
   */
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
=======
  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
      phone_ = s;
=======
      password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      return s;
    }
  }
  /**
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
   * <code>string phone = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
=======
   * <code>string password = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
      phone_ = b;
=======
      password_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
    }
    if (!getPhoneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phone_);
=======
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
    }
    if (!getPhoneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phone_);
=======
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.service.grpc.RegistrationInformationRequest)) {
      return super.equals(obj);
    }
    web.service.grpc.RegistrationInformationRequest other = (web.service.grpc.RegistrationInformationRequest) obj;

    boolean result = true;
    result = result && getEmail()
        .equals(other.getEmail());
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && getPhone()
        .equals(other.getPhone());
=======
    result = result && getPassword()
        .equals(other.getPassword());
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPhone().hashCode();
=======
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.RegistrationInformationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.service.grpc.RegistrationInformationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.RegistrationInformationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.service.grpc.RegistrationInformationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RegistrationInformationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RegistrationInformationRequest)
      web.service.grpc.RegistrationInformationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.grpc.User.internal_static_RegistrationInformationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.grpc.User.internal_static_RegistrationInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.grpc.RegistrationInformationRequest.class, web.service.grpc.RegistrationInformationRequest.Builder.class);
    }

    // Construct using web.service.grpc.RegistrationInformationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      email_ = "";
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java

      userName_ = "";

      phone_ = "";
=======

      password_ = "";
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.service.grpc.User.internal_static_RegistrationInformationRequest_descriptor;
    }

    public web.service.grpc.RegistrationInformationRequest getDefaultInstanceForType() {
      return web.service.grpc.RegistrationInformationRequest.getDefaultInstance();
    }

    public web.service.grpc.RegistrationInformationRequest build() {
      web.service.grpc.RegistrationInformationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    public web.service.grpc.RegistrationInformationRequest buildPartial() {
      web.service.grpc.RegistrationInformationRequest result = new web.service.grpc.RegistrationInformationRequest(this);
      result.email_ = email_;
      result.userName_ = userName_;
      result.phone_ = phone_;
=======
    public web.service.grpc.CreateUserRequest buildPartial() {
      web.service.grpc.CreateUserRequest result = new web.service.grpc.CreateUserRequest(this);
      result.email_ = email_;
      result.password_ = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.service.grpc.RegistrationInformationRequest) {
        return mergeFrom((web.service.grpc.RegistrationInformationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    public Builder mergeFrom(web.service.grpc.RegistrationInformationRequest other) {
      if (other == web.service.grpc.RegistrationInformationRequest.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getPhone().isEmpty()) {
        phone_ = other.phone_;
=======
    public Builder mergeFrom(web.service.grpc.CreateUserRequest other) {
      if (other == web.service.grpc.CreateUserRequest.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.service.grpc.RegistrationInformationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.service.grpc.RegistrationInformationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 2;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 2;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 2;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <code>string phone = 3;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
=======
    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
        phone_ = s;
=======
        password_ = s;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
     * <code>string phone = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
=======
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
        phone_ = b;
=======
        password_ = b;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
     * <code>string phone = 3;</code>
     */
    public Builder setPhone(
=======
     * <code>string password = 3;</code>
     */
    public Builder setPassword(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
      phone_ = value;
=======
      password_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
     * <code>string phone = 3;</code>
     */
    public Builder clearPhone() {
      
      phone_ = getDefaultInstance().getPhone();
=======
     * <code>string password = 3;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      onChanged();
      return this;
    }
    /**
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
     * <code>string phone = 3;</code>
     */
    public Builder setPhoneBytes(
=======
     * <code>string password = 3;</code>
     */
    public Builder setPasswordBytes(
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
<<<<<<< HEAD:src/main/java/web/service/grpc/RegistrationInformationRequest.java
      phone_ = value;
=======
      password_ = value;
>>>>>>> 9b8dd66da2f07a3f0507aa11aaef286e586c621f:src/main/java/web/service/grpc/CreateUserRequest.java
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RegistrationInformationRequest)
  }

  // @@protoc_insertion_point(class_scope:RegistrationInformationRequest)
  private static final web.service.grpc.RegistrationInformationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.service.grpc.RegistrationInformationRequest();
  }

  public static web.service.grpc.RegistrationInformationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegistrationInformationRequest>
      PARSER = new com.google.protobuf.AbstractParser<RegistrationInformationRequest>() {
    public RegistrationInformationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegistrationInformationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegistrationInformationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegistrationInformationRequest> getParserForType() {
    return PARSER;
  }

  public web.service.grpc.RegistrationInformationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

