// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

public interface CreateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
