// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

public interface PasswordResetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PasswordResetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool sent = 1;</code>
   */
  boolean getSent();
}
