// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

public interface RegistrationInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
