// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc;

/**
 * Protobuf service {@code UserService}
 */
public  abstract class UserService
    implements com.google.protobuf.Service {
  protected UserService() {}

  public interface Interface {
    /**
     * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
     */
    public abstract void registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.service.grpc.RegistrationResponseGrpc> done);

    /**
     * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
     */
    public abstract void login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.LoginRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.LoginResponse> done);

    /**
     * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
     */
    public abstract void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.ConfirmEmailResponse> done);

    /**
     * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
     */
    public abstract void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.PasswordResetResponse> done);

    /**
     * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
     */
    public abstract void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.RegistrationInformationResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new UserService() {
      @java.lang.Override
      public  void registration(
          com.google.protobuf.RpcController controller,
          web.service.grpc.RegistrationRequestGrpc request,
          com.google.protobuf.RpcCallback<web.service.grpc.RegistrationResponseGrpc> done) {
        impl.registration(controller, request, done);
      }

      @java.lang.Override
      public  void login(
          com.google.protobuf.RpcController controller,
          web.service.grpc.LoginRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.LoginResponse> done) {
        impl.login(controller, request, done);
      }

      @java.lang.Override
      public  void verificationTokenRegistration(
          com.google.protobuf.RpcController controller,
          web.service.grpc.ConfirmEmailRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.ConfirmEmailResponse> done) {
        impl.verificationTokenRegistration(controller, request, done);
      }

      @java.lang.Override
      public  void passwordForgot(
          com.google.protobuf.RpcController controller,
          web.service.grpc.PasswordResetRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.PasswordResetResponse> done) {
        impl.passwordForgot(controller, request, done);
      }

      @java.lang.Override
      public  void registrationInformation(
          com.google.protobuf.RpcController controller,
          web.service.grpc.RegistrationInformationRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.RegistrationInformationResponse> done) {
        impl.registrationInformation(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.registration(controller, (web.service.grpc.RegistrationRequestGrpc)request);
          case 1:
            return impl.login(controller, (web.service.grpc.LoginRequest)request);
          case 2:
            return impl.verificationTokenRegistration(controller, (web.service.grpc.ConfirmEmailRequest)request);
          case 3:
            return impl.passwordForgot(controller, (web.service.grpc.PasswordResetRequest)request);
          case 4:
            return impl.registrationInformation(controller, (web.service.grpc.RegistrationInformationRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.RegistrationRequestGrpc.getDefaultInstance();
          case 1:
            return web.service.grpc.LoginRequest.getDefaultInstance();
          case 2:
            return web.service.grpc.ConfirmEmailRequest.getDefaultInstance();
          case 3:
            return web.service.grpc.PasswordResetRequest.getDefaultInstance();
          case 4:
            return web.service.grpc.RegistrationInformationRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.RegistrationResponseGrpc.getDefaultInstance();
          case 1:
            return web.service.grpc.LoginResponse.getDefaultInstance();
          case 2:
            return web.service.grpc.ConfirmEmailResponse.getDefaultInstance();
          case 3:
            return web.service.grpc.PasswordResetResponse.getDefaultInstance();
          case 4:
            return web.service.grpc.RegistrationInformationResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
   */
  public abstract void registration(
      com.google.protobuf.RpcController controller,
      web.service.grpc.RegistrationRequestGrpc request,
      com.google.protobuf.RpcCallback<web.service.grpc.RegistrationResponseGrpc> done);

  /**
   * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
   */
  public abstract void login(
      com.google.protobuf.RpcController controller,
      web.service.grpc.LoginRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.LoginResponse> done);

  /**
   * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
   */
  public abstract void verificationTokenRegistration(
      com.google.protobuf.RpcController controller,
      web.service.grpc.ConfirmEmailRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.ConfirmEmailResponse> done);

  /**
   * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
   */
  public abstract void passwordForgot(
      com.google.protobuf.RpcController controller,
      web.service.grpc.PasswordResetRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.PasswordResetResponse> done);

  /**
   * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
   */
  public abstract void registrationInformation(
      com.google.protobuf.RpcController controller,
      web.service.grpc.RegistrationInformationRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.RegistrationInformationResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return web.service.grpc.User.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.registration(controller, (web.service.grpc.RegistrationRequestGrpc)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.RegistrationResponseGrpc>specializeCallback(
            done));
        return;
      case 1:
        this.login(controller, (web.service.grpc.LoginRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.LoginResponse>specializeCallback(
            done));
        return;
      case 2:
        this.verificationTokenRegistration(controller, (web.service.grpc.ConfirmEmailRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.ConfirmEmailResponse>specializeCallback(
            done));
        return;
      case 3:
        this.passwordForgot(controller, (web.service.grpc.PasswordResetRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.PasswordResetResponse>specializeCallback(
            done));
        return;
      case 4:
        this.registrationInformation(controller, (web.service.grpc.RegistrationInformationRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.RegistrationInformationResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.RegistrationRequestGrpc.getDefaultInstance();
      case 1:
        return web.service.grpc.LoginRequest.getDefaultInstance();
      case 2:
        return web.service.grpc.ConfirmEmailRequest.getDefaultInstance();
      case 3:
        return web.service.grpc.PasswordResetRequest.getDefaultInstance();
      case 4:
        return web.service.grpc.RegistrationInformationRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.RegistrationResponseGrpc.getDefaultInstance();
      case 1:
        return web.service.grpc.LoginResponse.getDefaultInstance();
      case 2:
        return web.service.grpc.ConfirmEmailResponse.getDefaultInstance();
      case 3:
        return web.service.grpc.PasswordResetResponse.getDefaultInstance();
      case 4:
        return web.service.grpc.RegistrationInformationResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends web.service.grpc.UserService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.service.grpc.RegistrationResponseGrpc> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.RegistrationResponseGrpc.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.RegistrationResponseGrpc.class,
          web.service.grpc.RegistrationResponseGrpc.getDefaultInstance()));
    }

    public  void login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.LoginRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.LoginResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.LoginResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.LoginResponse.class,
          web.service.grpc.LoginResponse.getDefaultInstance()));
    }

    public  void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.ConfirmEmailResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.ConfirmEmailResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.ConfirmEmailResponse.class,
          web.service.grpc.ConfirmEmailResponse.getDefaultInstance()));
    }

    public  void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.PasswordResetResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.PasswordResetResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.PasswordResetResponse.class,
          web.service.grpc.PasswordResetResponse.getDefaultInstance()));
    }

    public  void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.RegistrationInformationResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.RegistrationInformationResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.RegistrationInformationResponse.class,
          web.service.grpc.RegistrationInformationResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public web.service.grpc.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.LoginRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public web.service.grpc.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.RegistrationResponseGrpc) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.RegistrationResponseGrpc.getDefaultInstance());
    }


    public web.service.grpc.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.LoginRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.LoginResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.LoginResponse.getDefaultInstance());
    }


    public web.service.grpc.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.ConfirmEmailResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.ConfirmEmailResponse.getDefaultInstance());
    }


    public web.service.grpc.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.PasswordResetResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.PasswordResetResponse.getDefaultInstance());
    }


    public web.service.grpc.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.RegistrationInformationResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.RegistrationInformationResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:UserService)
}

