// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.grpc.user;

/**
 * Protobuf service {@code UserService}
 */
public  abstract class UserService
    implements com.google.protobuf.Service {
  protected UserService() {}

  public interface Interface {
    /**
     * <pre>
     * create a new account, save new email, password and send verification email
     * </pre>
     *
     * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
     */
    public abstract void registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationResponseGrpc> done);

    /**
     * <pre>
     * login account
     * </pre>
     *
     * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
     */
    public abstract void login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.LoginRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.LoginResponse> done);

    /**
     * <pre>
     * Verify email
     * </pre>
     *
     * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
     */
    public abstract void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.ConfirmEmailResponse> done);

    /**
     * <pre>
     * send reset password email
     * </pre>
     *
     * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
     */
    public abstract void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.PasswordResetResponse> done);

    /**
     * <pre>
     * save new password
     * </pre>
     *
     * <code>rpc PasswordReset(.NewPasswordRequest) returns (.NewPasswordResponse);</code>
     */
    public abstract void passwordReset(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.NewPasswordRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.NewPasswordResponse> done);

    /**
     * <pre>
     * register account's information
     * </pre>
     *
     * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
     */
    public abstract void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationInformationResponse> done);

    /**
     * <pre>
     * verify reset password token
     * </pre>
     *
     * <code>rpc VerificationResetPasswordToken(.VerificationResetPasswordTokenRequest) returns (.VerificationResetPasswordTokenResponse);</code>
     */
    public abstract void verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.VerificationResetPasswordTokenRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.VerificationResetPasswordTokenResponse> done);

    /**
     * <pre>
     * filter controller call to user service
     * </pre>
     *
     * <code>rpc GetEmailFromToken(.GetEmailRequest) returns (.GetEmailResponse);</code>
     */
    public abstract void getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.GetEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.GetEmailResponse> done);

    /**
     * <pre>
     *validate toke
     * </pre>
     *
     * <code>rpc ValidateToken(.ValidateTokenRequest) returns (.ValidateTokenResponse);</code>
     */
    public abstract void validateToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ValidateTokenRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.ValidateTokenResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new UserService() {
      @java.lang.Override
      public  void registration(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.RegistrationRequestGrpc request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationResponseGrpc> done) {
        impl.registration(controller, request, done);
      }

      @java.lang.Override
      public  void login(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.LoginRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.LoginResponse> done) {
        impl.login(controller, request, done);
      }

      @java.lang.Override
      public  void verificationTokenRegistration(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.ConfirmEmailRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.ConfirmEmailResponse> done) {
        impl.verificationTokenRegistration(controller, request, done);
      }

      @java.lang.Override
      public  void passwordForgot(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.PasswordResetRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.PasswordResetResponse> done) {
        impl.passwordForgot(controller, request, done);
      }

      @java.lang.Override
      public  void passwordReset(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.NewPasswordRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.NewPasswordResponse> done) {
        impl.passwordReset(controller, request, done);
      }

      @java.lang.Override
      public  void registrationInformation(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.RegistrationInformationRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationInformationResponse> done) {
        impl.registrationInformation(controller, request, done);
      }

      @java.lang.Override
      public  void verificationResetPasswordToken(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.VerificationResetPasswordTokenRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.VerificationResetPasswordTokenResponse> done) {
        impl.verificationResetPasswordToken(controller, request, done);
      }

      @java.lang.Override
      public  void getEmailFromToken(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.GetEmailRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.GetEmailResponse> done) {
        impl.getEmailFromToken(controller, request, done);
      }

      @java.lang.Override
      public  void validateToken(
          com.google.protobuf.RpcController controller,
          web.service.grpc.user.ValidateTokenRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.user.ValidateTokenResponse> done) {
        impl.validateToken(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.registration(controller, (web.service.grpc.user.RegistrationRequestGrpc)request);
          case 1:
            return impl.login(controller, (web.service.grpc.user.LoginRequest)request);
          case 2:
            return impl.verificationTokenRegistration(controller, (web.service.grpc.user.ConfirmEmailRequest)request);
          case 3:
            return impl.passwordForgot(controller, (web.service.grpc.user.PasswordResetRequest)request);
          case 4:
            return impl.passwordReset(controller, (web.service.grpc.user.NewPasswordRequest)request);
          case 5:
            return impl.registrationInformation(controller, (web.service.grpc.user.RegistrationInformationRequest)request);
          case 6:
            return impl.verificationResetPasswordToken(controller, (web.service.grpc.user.VerificationResetPasswordTokenRequest)request);
          case 7:
            return impl.getEmailFromToken(controller, (web.service.grpc.user.GetEmailRequest)request);
          case 8:
            return impl.validateToken(controller, (web.service.grpc.user.ValidateTokenRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.user.RegistrationRequestGrpc.getDefaultInstance();
          case 1:
            return web.service.grpc.user.LoginRequest.getDefaultInstance();
          case 2:
            return web.service.grpc.user.ConfirmEmailRequest.getDefaultInstance();
          case 3:
            return web.service.grpc.user.PasswordResetRequest.getDefaultInstance();
          case 4:
            return web.service.grpc.user.NewPasswordRequest.getDefaultInstance();
          case 5:
            return web.service.grpc.user.RegistrationInformationRequest.getDefaultInstance();
          case 6:
            return web.service.grpc.user.VerificationResetPasswordTokenRequest.getDefaultInstance();
          case 7:
            return web.service.grpc.user.GetEmailRequest.getDefaultInstance();
          case 8:
            return web.service.grpc.user.ValidateTokenRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.user.RegistrationResponseGrpc.getDefaultInstance();
          case 1:
            return web.service.grpc.user.LoginResponse.getDefaultInstance();
          case 2:
            return web.service.grpc.user.ConfirmEmailResponse.getDefaultInstance();
          case 3:
            return web.service.grpc.user.PasswordResetResponse.getDefaultInstance();
          case 4:
            return web.service.grpc.user.NewPasswordResponse.getDefaultInstance();
          case 5:
            return web.service.grpc.user.RegistrationInformationResponse.getDefaultInstance();
          case 6:
            return web.service.grpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance();
          case 7:
            return web.service.grpc.user.GetEmailResponse.getDefaultInstance();
          case 8:
            return web.service.grpc.user.ValidateTokenResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * create a new account, save new email, password and send verification email
   * </pre>
   *
   * <code>rpc Registration(.RegistrationRequestGrpc) returns (.RegistrationResponseGrpc);</code>
   */
  public abstract void registration(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.RegistrationRequestGrpc request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationResponseGrpc> done);

  /**
   * <pre>
   * login account
   * </pre>
   *
   * <code>rpc Login(.LoginRequest) returns (.LoginResponse);</code>
   */
  public abstract void login(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.LoginRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.LoginResponse> done);

  /**
   * <pre>
   * Verify email
   * </pre>
   *
   * <code>rpc VerificationTokenRegistration(.ConfirmEmailRequest) returns (.ConfirmEmailResponse);</code>
   */
  public abstract void verificationTokenRegistration(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.ConfirmEmailRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.ConfirmEmailResponse> done);

  /**
   * <pre>
   * send reset password email
   * </pre>
   *
   * <code>rpc PasswordForgot(.PasswordResetRequest) returns (.PasswordResetResponse);</code>
   */
  public abstract void passwordForgot(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.PasswordResetRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.PasswordResetResponse> done);

  /**
   * <pre>
   * save new password
   * </pre>
   *
   * <code>rpc PasswordReset(.NewPasswordRequest) returns (.NewPasswordResponse);</code>
   */
  public abstract void passwordReset(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.NewPasswordRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.NewPasswordResponse> done);

  /**
   * <pre>
   * register account's information
   * </pre>
   *
   * <code>rpc RegistrationInformation(.RegistrationInformationRequest) returns (.RegistrationInformationResponse);</code>
   */
  public abstract void registrationInformation(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.RegistrationInformationRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationInformationResponse> done);

  /**
   * <pre>
   * verify reset password token
   * </pre>
   *
   * <code>rpc VerificationResetPasswordToken(.VerificationResetPasswordTokenRequest) returns (.VerificationResetPasswordTokenResponse);</code>
   */
  public abstract void verificationResetPasswordToken(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.VerificationResetPasswordTokenRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.VerificationResetPasswordTokenResponse> done);

  /**
   * <pre>
   * filter controller call to user service
   * </pre>
   *
   * <code>rpc GetEmailFromToken(.GetEmailRequest) returns (.GetEmailResponse);</code>
   */
  public abstract void getEmailFromToken(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.GetEmailRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.GetEmailResponse> done);

  /**
   * <pre>
   *validate toke
   * </pre>
   *
   * <code>rpc ValidateToken(.ValidateTokenRequest) returns (.ValidateTokenResponse);</code>
   */
  public abstract void validateToken(
      com.google.protobuf.RpcController controller,
      web.service.grpc.user.ValidateTokenRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.user.ValidateTokenResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return web.service.grpc.user.User.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.registration(controller, (web.service.grpc.user.RegistrationRequestGrpc)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.RegistrationResponseGrpc>specializeCallback(
            done));
        return;
      case 1:
        this.login(controller, (web.service.grpc.user.LoginRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.LoginResponse>specializeCallback(
            done));
        return;
      case 2:
        this.verificationTokenRegistration(controller, (web.service.grpc.user.ConfirmEmailRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.ConfirmEmailResponse>specializeCallback(
            done));
        return;
      case 3:
        this.passwordForgot(controller, (web.service.grpc.user.PasswordResetRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.PasswordResetResponse>specializeCallback(
            done));
        return;
      case 4:
        this.passwordReset(controller, (web.service.grpc.user.NewPasswordRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.NewPasswordResponse>specializeCallback(
            done));
        return;
      case 5:
        this.registrationInformation(controller, (web.service.grpc.user.RegistrationInformationRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.RegistrationInformationResponse>specializeCallback(
            done));
        return;
      case 6:
        this.verificationResetPasswordToken(controller, (web.service.grpc.user.VerificationResetPasswordTokenRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.VerificationResetPasswordTokenResponse>specializeCallback(
            done));
        return;
      case 7:
        this.getEmailFromToken(controller, (web.service.grpc.user.GetEmailRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.GetEmailResponse>specializeCallback(
            done));
        return;
      case 8:
        this.validateToken(controller, (web.service.grpc.user.ValidateTokenRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.user.ValidateTokenResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.user.RegistrationRequestGrpc.getDefaultInstance();
      case 1:
        return web.service.grpc.user.LoginRequest.getDefaultInstance();
      case 2:
        return web.service.grpc.user.ConfirmEmailRequest.getDefaultInstance();
      case 3:
        return web.service.grpc.user.PasswordResetRequest.getDefaultInstance();
      case 4:
        return web.service.grpc.user.NewPasswordRequest.getDefaultInstance();
      case 5:
        return web.service.grpc.user.RegistrationInformationRequest.getDefaultInstance();
      case 6:
        return web.service.grpc.user.VerificationResetPasswordTokenRequest.getDefaultInstance();
      case 7:
        return web.service.grpc.user.GetEmailRequest.getDefaultInstance();
      case 8:
        return web.service.grpc.user.ValidateTokenRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.user.RegistrationResponseGrpc.getDefaultInstance();
      case 1:
        return web.service.grpc.user.LoginResponse.getDefaultInstance();
      case 2:
        return web.service.grpc.user.ConfirmEmailResponse.getDefaultInstance();
      case 3:
        return web.service.grpc.user.PasswordResetResponse.getDefaultInstance();
      case 4:
        return web.service.grpc.user.NewPasswordResponse.getDefaultInstance();
      case 5:
        return web.service.grpc.user.RegistrationInformationResponse.getDefaultInstance();
      case 6:
        return web.service.grpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance();
      case 7:
        return web.service.grpc.user.GetEmailResponse.getDefaultInstance();
      case 8:
        return web.service.grpc.user.ValidateTokenResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends web.service.grpc.user.UserService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationRequestGrpc request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationResponseGrpc> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.user.RegistrationResponseGrpc.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.RegistrationResponseGrpc.class,
          web.service.grpc.user.RegistrationResponseGrpc.getDefaultInstance()));
    }

    public  void login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.LoginRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.LoginResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.user.LoginResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.LoginResponse.class,
          web.service.grpc.user.LoginResponse.getDefaultInstance()));
    }

    public  void verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ConfirmEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.ConfirmEmailResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.user.ConfirmEmailResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.ConfirmEmailResponse.class,
          web.service.grpc.user.ConfirmEmailResponse.getDefaultInstance()));
    }

    public  void passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.PasswordResetRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.PasswordResetResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.user.PasswordResetResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.PasswordResetResponse.class,
          web.service.grpc.user.PasswordResetResponse.getDefaultInstance()));
    }

    public  void passwordReset(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.NewPasswordRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.NewPasswordResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.user.NewPasswordResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.NewPasswordResponse.class,
          web.service.grpc.user.NewPasswordResponse.getDefaultInstance()));
    }

    public  void registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationInformationRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.RegistrationInformationResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.service.grpc.user.RegistrationInformationResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.RegistrationInformationResponse.class,
          web.service.grpc.user.RegistrationInformationResponse.getDefaultInstance()));
    }

    public  void verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.VerificationResetPasswordTokenRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.VerificationResetPasswordTokenResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(6),
        controller,
        request,
        web.service.grpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.VerificationResetPasswordTokenResponse.class,
          web.service.grpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance()));
    }

    public  void getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.GetEmailRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.GetEmailResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(7),
        controller,
        request,
        web.service.grpc.user.GetEmailResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.GetEmailResponse.class,
          web.service.grpc.user.GetEmailResponse.getDefaultInstance()));
    }

    public  void validateToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ValidateTokenRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.user.ValidateTokenResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(8),
        controller,
        request,
        web.service.grpc.user.ValidateTokenResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.user.ValidateTokenResponse.class,
          web.service.grpc.user.ValidateTokenResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public web.service.grpc.user.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.LoginRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.NewPasswordResponse passwordReset(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.NewPasswordRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.VerificationResetPasswordTokenResponse verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.VerificationResetPasswordTokenRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.GetEmailResponse getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.GetEmailRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.user.ValidateTokenResponse validateToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ValidateTokenRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public web.service.grpc.user.RegistrationResponseGrpc registration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationRequestGrpc request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.RegistrationResponseGrpc) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.user.RegistrationResponseGrpc.getDefaultInstance());
    }


    public web.service.grpc.user.LoginResponse login(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.LoginRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.LoginResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.user.LoginResponse.getDefaultInstance());
    }


    public web.service.grpc.user.ConfirmEmailResponse verificationTokenRegistration(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ConfirmEmailRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.ConfirmEmailResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.user.ConfirmEmailResponse.getDefaultInstance());
    }


    public web.service.grpc.user.PasswordResetResponse passwordForgot(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.PasswordResetRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.PasswordResetResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.user.PasswordResetResponse.getDefaultInstance());
    }


    public web.service.grpc.user.NewPasswordResponse passwordReset(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.NewPasswordRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.NewPasswordResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.user.NewPasswordResponse.getDefaultInstance());
    }


    public web.service.grpc.user.RegistrationInformationResponse registrationInformation(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.RegistrationInformationRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.RegistrationInformationResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.service.grpc.user.RegistrationInformationResponse.getDefaultInstance());
    }


    public web.service.grpc.user.VerificationResetPasswordTokenResponse verificationResetPasswordToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.VerificationResetPasswordTokenRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.VerificationResetPasswordTokenResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(6),
        controller,
        request,
        web.service.grpc.user.VerificationResetPasswordTokenResponse.getDefaultInstance());
    }


    public web.service.grpc.user.GetEmailResponse getEmailFromToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.GetEmailRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.GetEmailResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(7),
        controller,
        request,
        web.service.grpc.user.GetEmailResponse.getDefaultInstance());
    }


    public web.service.grpc.user.ValidateTokenResponse validateToken(
        com.google.protobuf.RpcController controller,
        web.service.grpc.user.ValidateTokenRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.user.ValidateTokenResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(8),
        controller,
        request,
        web.service.grpc.user.ValidateTokenResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:UserService)
}

