// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.grpc.newsfeed;

public interface GetNewsFeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetNewsFeedRequest)
    com.google.protobuf.MessageOrBuilder {
}
