// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.grpc.newsfeed;

public interface LikeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LikeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <code>int64 postId = 2;</code>
   */
  long getPostId();
}
