// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.grpc.newsfeed;

/**
 * Protobuf service {@code NewsFeedService}
 */
public  abstract class NewsFeedService
    implements com.google.protobuf.Service {
  protected NewsFeedService() {}

  public interface Interface {
    /**
     * <code>rpc getNewsFeed(.GetNewsFeedRequest) returns (.GetNewsFeedResponse);</code>
     */
    public abstract void getNewsFeed(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.GetNewsFeedRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.GetNewsFeedResponse> done);

    /**
     * <code>rpc saveNewPost(.Post) returns (.SaveNewPostResponse);</code>
     */
    public abstract void saveNewPost(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.Post request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.SaveNewPostResponse> done);

    /**
     * <code>rpc like(.LikeRequest) returns (.LikeResponse);</code>
     */
    public abstract void like(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.LikeRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.LikeResponse> done);

    /**
     * <code>rpc share(.ShareRequest) returns (.ShareResponse);</code>
     */
    public abstract void share(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.ShareRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.ShareResponse> done);

    /**
     * <code>rpc comment(.CommentRequest) returns (.CommentResponse);</code>
     */
    public abstract void comment(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.CommentRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.CommentResponse> done);

    /**
     * <code>rpc tag(.TagRequest) returns (.TagResponse);</code>
     */
    public abstract void tag(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.TagRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.TagResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new NewsFeedService() {
      @java.lang.Override
      public  void getNewsFeed(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.GetNewsFeedRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.GetNewsFeedResponse> done) {
        impl.getNewsFeed(controller, request, done);
      }

      @java.lang.Override
      public  void saveNewPost(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.Post request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.SaveNewPostResponse> done) {
        impl.saveNewPost(controller, request, done);
      }

      @java.lang.Override
      public  void like(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.LikeRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.LikeResponse> done) {
        impl.like(controller, request, done);
      }

      @java.lang.Override
      public  void share(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.ShareRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.ShareResponse> done) {
        impl.share(controller, request, done);
      }

      @java.lang.Override
      public  void comment(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.CommentRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.CommentResponse> done) {
        impl.comment(controller, request, done);
      }

      @java.lang.Override
      public  void tag(
          com.google.protobuf.RpcController controller,
          web.service.grpc.newsfeed.TagRequest request,
          com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.TagResponse> done) {
        impl.tag(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.getNewsFeed(controller, (web.service.grpc.newsfeed.GetNewsFeedRequest)request);
          case 1:
            return impl.saveNewPost(controller, (web.service.grpc.newsfeed.Post)request);
          case 2:
            return impl.like(controller, (web.service.grpc.newsfeed.LikeRequest)request);
          case 3:
            return impl.share(controller, (web.service.grpc.newsfeed.ShareRequest)request);
          case 4:
            return impl.comment(controller, (web.service.grpc.newsfeed.CommentRequest)request);
          case 5:
            return impl.tag(controller, (web.service.grpc.newsfeed.TagRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.newsfeed.GetNewsFeedRequest.getDefaultInstance();
          case 1:
            return web.service.grpc.newsfeed.Post.getDefaultInstance();
          case 2:
            return web.service.grpc.newsfeed.LikeRequest.getDefaultInstance();
          case 3:
            return web.service.grpc.newsfeed.ShareRequest.getDefaultInstance();
          case 4:
            return web.service.grpc.newsfeed.CommentRequest.getDefaultInstance();
          case 5:
            return web.service.grpc.newsfeed.TagRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.grpc.newsfeed.GetNewsFeedResponse.getDefaultInstance();
          case 1:
            return web.service.grpc.newsfeed.SaveNewPostResponse.getDefaultInstance();
          case 2:
            return web.service.grpc.newsfeed.LikeResponse.getDefaultInstance();
          case 3:
            return web.service.grpc.newsfeed.ShareResponse.getDefaultInstance();
          case 4:
            return web.service.grpc.newsfeed.CommentResponse.getDefaultInstance();
          case 5:
            return web.service.grpc.newsfeed.TagResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc getNewsFeed(.GetNewsFeedRequest) returns (.GetNewsFeedResponse);</code>
   */
  public abstract void getNewsFeed(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.GetNewsFeedRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.GetNewsFeedResponse> done);

  /**
   * <code>rpc saveNewPost(.Post) returns (.SaveNewPostResponse);</code>
   */
  public abstract void saveNewPost(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.Post request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.SaveNewPostResponse> done);

  /**
   * <code>rpc like(.LikeRequest) returns (.LikeResponse);</code>
   */
  public abstract void like(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.LikeRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.LikeResponse> done);

  /**
   * <code>rpc share(.ShareRequest) returns (.ShareResponse);</code>
   */
  public abstract void share(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.ShareRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.ShareResponse> done);

  /**
   * <code>rpc comment(.CommentRequest) returns (.CommentResponse);</code>
   */
  public abstract void comment(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.CommentRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.CommentResponse> done);

  /**
   * <code>rpc tag(.TagRequest) returns (.TagResponse);</code>
   */
  public abstract void tag(
      com.google.protobuf.RpcController controller,
      web.service.grpc.newsfeed.TagRequest request,
      com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.TagResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return web.service.grpc.newsfeed.Newsfeed.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.getNewsFeed(controller, (web.service.grpc.newsfeed.GetNewsFeedRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.GetNewsFeedResponse>specializeCallback(
            done));
        return;
      case 1:
        this.saveNewPost(controller, (web.service.grpc.newsfeed.Post)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.SaveNewPostResponse>specializeCallback(
            done));
        return;
      case 2:
        this.like(controller, (web.service.grpc.newsfeed.LikeRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.LikeResponse>specializeCallback(
            done));
        return;
      case 3:
        this.share(controller, (web.service.grpc.newsfeed.ShareRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.ShareResponse>specializeCallback(
            done));
        return;
      case 4:
        this.comment(controller, (web.service.grpc.newsfeed.CommentRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.CommentResponse>specializeCallback(
            done));
        return;
      case 5:
        this.tag(controller, (web.service.grpc.newsfeed.TagRequest)request,
          com.google.protobuf.RpcUtil.<web.service.grpc.newsfeed.TagResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.newsfeed.GetNewsFeedRequest.getDefaultInstance();
      case 1:
        return web.service.grpc.newsfeed.Post.getDefaultInstance();
      case 2:
        return web.service.grpc.newsfeed.LikeRequest.getDefaultInstance();
      case 3:
        return web.service.grpc.newsfeed.ShareRequest.getDefaultInstance();
      case 4:
        return web.service.grpc.newsfeed.CommentRequest.getDefaultInstance();
      case 5:
        return web.service.grpc.newsfeed.TagRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.grpc.newsfeed.GetNewsFeedResponse.getDefaultInstance();
      case 1:
        return web.service.grpc.newsfeed.SaveNewPostResponse.getDefaultInstance();
      case 2:
        return web.service.grpc.newsfeed.LikeResponse.getDefaultInstance();
      case 3:
        return web.service.grpc.newsfeed.ShareResponse.getDefaultInstance();
      case 4:
        return web.service.grpc.newsfeed.CommentResponse.getDefaultInstance();
      case 5:
        return web.service.grpc.newsfeed.TagResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends web.service.grpc.newsfeed.NewsFeedService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void getNewsFeed(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.GetNewsFeedRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.GetNewsFeedResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.newsfeed.GetNewsFeedResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.GetNewsFeedResponse.class,
          web.service.grpc.newsfeed.GetNewsFeedResponse.getDefaultInstance()));
    }

    public  void saveNewPost(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.Post request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.SaveNewPostResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.newsfeed.SaveNewPostResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.SaveNewPostResponse.class,
          web.service.grpc.newsfeed.SaveNewPostResponse.getDefaultInstance()));
    }

    public  void like(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.LikeRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.LikeResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.newsfeed.LikeResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.LikeResponse.class,
          web.service.grpc.newsfeed.LikeResponse.getDefaultInstance()));
    }

    public  void share(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.ShareRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.ShareResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.newsfeed.ShareResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.ShareResponse.class,
          web.service.grpc.newsfeed.ShareResponse.getDefaultInstance()));
    }

    public  void comment(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.CommentRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.CommentResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.newsfeed.CommentResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.CommentResponse.class,
          web.service.grpc.newsfeed.CommentResponse.getDefaultInstance()));
    }

    public  void tag(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.TagRequest request,
        com.google.protobuf.RpcCallback<web.service.grpc.newsfeed.TagResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.service.grpc.newsfeed.TagResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.grpc.newsfeed.TagResponse.class,
          web.service.grpc.newsfeed.TagResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public web.service.grpc.newsfeed.GetNewsFeedResponse getNewsFeed(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.GetNewsFeedRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.newsfeed.SaveNewPostResponse saveNewPost(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.Post request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.newsfeed.LikeResponse like(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.LikeRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.newsfeed.ShareResponse share(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.ShareRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.newsfeed.CommentResponse comment(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.CommentRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.grpc.newsfeed.TagResponse tag(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.TagRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public web.service.grpc.newsfeed.GetNewsFeedResponse getNewsFeed(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.GetNewsFeedRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.GetNewsFeedResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.grpc.newsfeed.GetNewsFeedResponse.getDefaultInstance());
    }


    public web.service.grpc.newsfeed.SaveNewPostResponse saveNewPost(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.Post request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.SaveNewPostResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.grpc.newsfeed.SaveNewPostResponse.getDefaultInstance());
    }


    public web.service.grpc.newsfeed.LikeResponse like(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.LikeRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.LikeResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        web.service.grpc.newsfeed.LikeResponse.getDefaultInstance());
    }


    public web.service.grpc.newsfeed.ShareResponse share(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.ShareRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.ShareResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        web.service.grpc.newsfeed.ShareResponse.getDefaultInstance());
    }


    public web.service.grpc.newsfeed.CommentResponse comment(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.CommentRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.CommentResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        web.service.grpc.newsfeed.CommentResponse.getDefaultInstance());
    }


    public web.service.grpc.newsfeed.TagResponse tag(
        com.google.protobuf.RpcController controller,
        web.service.grpc.newsfeed.TagRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.grpc.newsfeed.TagResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        web.service.grpc.newsfeed.TagResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:NewsFeedService)
}

