// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.grpc.newsfeed;

/**
 * Protobuf type {@code Post}
 */
public  final class Post extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Post)
    PostOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Post.newBuilder() to construct.
  private Post(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Post() {
    id_ = 0L;
    userId_ = 0L;
    content_ = "";
    comments_ = java.util.Collections.emptyList();
    likes_ = java.util.Collections.emptyList();
    shares_ = java.util.Collections.emptyList();
    tags_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Post(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            userId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              comments_ = new java.util.ArrayList<web.service.grpc.newsfeed.Comment>();
              mutable_bitField0_ |= 0x00000008;
            }
            comments_.add(
                input.readMessage(web.service.grpc.newsfeed.Comment.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              likes_ = new java.util.ArrayList<web.service.grpc.newsfeed.Like>();
              mutable_bitField0_ |= 0x00000010;
            }
            likes_.add(
                input.readMessage(web.service.grpc.newsfeed.Like.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              shares_ = new java.util.ArrayList<web.service.grpc.newsfeed.Share>();
              mutable_bitField0_ |= 0x00000020;
            }
            shares_.add(
                input.readMessage(web.service.grpc.newsfeed.Share.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              tags_ = new java.util.ArrayList<web.service.grpc.newsfeed.Tag>();
              mutable_bitField0_ |= 0x00000040;
            }
            tags_.add(
                input.readMessage(web.service.grpc.newsfeed.Tag.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        comments_ = java.util.Collections.unmodifiableList(comments_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        likes_ = java.util.Collections.unmodifiableList(likes_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        shares_ = java.util.Collections.unmodifiableList(shares_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        tags_ = java.util.Collections.unmodifiableList(tags_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.service.grpc.newsfeed.Newsfeed.internal_static_Post_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.service.grpc.newsfeed.Newsfeed.internal_static_Post_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.service.grpc.newsfeed.Post.class, web.service.grpc.newsfeed.Post.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private long userId_;
  /**
   * <code>int64 userId = 2;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 3;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 4;
  private java.util.List<web.service.grpc.newsfeed.Comment> comments_;
  /**
   * <code>repeated .Comment comments = 4;</code>
   */
  public java.util.List<web.service.grpc.newsfeed.Comment> getCommentsList() {
    return comments_;
  }
  /**
   * <code>repeated .Comment comments = 4;</code>
   */
  public java.util.List<? extends web.service.grpc.newsfeed.CommentOrBuilder> 
      getCommentsOrBuilderList() {
    return comments_;
  }
  /**
   * <code>repeated .Comment comments = 4;</code>
   */
  public int getCommentsCount() {
    return comments_.size();
  }
  /**
   * <code>repeated .Comment comments = 4;</code>
   */
  public web.service.grpc.newsfeed.Comment getComments(int index) {
    return comments_.get(index);
  }
  /**
   * <code>repeated .Comment comments = 4;</code>
   */
  public web.service.grpc.newsfeed.CommentOrBuilder getCommentsOrBuilder(
      int index) {
    return comments_.get(index);
  }

  public static final int LIKES_FIELD_NUMBER = 5;
  private java.util.List<web.service.grpc.newsfeed.Like> likes_;
  /**
   * <code>repeated .Like likes = 5;</code>
   */
  public java.util.List<web.service.grpc.newsfeed.Like> getLikesList() {
    return likes_;
  }
  /**
   * <code>repeated .Like likes = 5;</code>
   */
  public java.util.List<? extends web.service.grpc.newsfeed.LikeOrBuilder> 
      getLikesOrBuilderList() {
    return likes_;
  }
  /**
   * <code>repeated .Like likes = 5;</code>
   */
  public int getLikesCount() {
    return likes_.size();
  }
  /**
   * <code>repeated .Like likes = 5;</code>
   */
  public web.service.grpc.newsfeed.Like getLikes(int index) {
    return likes_.get(index);
  }
  /**
   * <code>repeated .Like likes = 5;</code>
   */
  public web.service.grpc.newsfeed.LikeOrBuilder getLikesOrBuilder(
      int index) {
    return likes_.get(index);
  }

  public static final int SHARES_FIELD_NUMBER = 6;
  private java.util.List<web.service.grpc.newsfeed.Share> shares_;
  /**
   * <code>repeated .Share shares = 6;</code>
   */
  public java.util.List<web.service.grpc.newsfeed.Share> getSharesList() {
    return shares_;
  }
  /**
   * <code>repeated .Share shares = 6;</code>
   */
  public java.util.List<? extends web.service.grpc.newsfeed.ShareOrBuilder> 
      getSharesOrBuilderList() {
    return shares_;
  }
  /**
   * <code>repeated .Share shares = 6;</code>
   */
  public int getSharesCount() {
    return shares_.size();
  }
  /**
   * <code>repeated .Share shares = 6;</code>
   */
  public web.service.grpc.newsfeed.Share getShares(int index) {
    return shares_.get(index);
  }
  /**
   * <code>repeated .Share shares = 6;</code>
   */
  public web.service.grpc.newsfeed.ShareOrBuilder getSharesOrBuilder(
      int index) {
    return shares_.get(index);
  }

  public static final int TAGS_FIELD_NUMBER = 7;
  private java.util.List<web.service.grpc.newsfeed.Tag> tags_;
  /**
   * <code>repeated .Tag tags = 7;</code>
   */
  public java.util.List<web.service.grpc.newsfeed.Tag> getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated .Tag tags = 7;</code>
   */
  public java.util.List<? extends web.service.grpc.newsfeed.TagOrBuilder> 
      getTagsOrBuilderList() {
    return tags_;
  }
  /**
   * <code>repeated .Tag tags = 7;</code>
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated .Tag tags = 7;</code>
   */
  public web.service.grpc.newsfeed.Tag getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated .Tag tags = 7;</code>
   */
  public web.service.grpc.newsfeed.TagOrBuilder getTagsOrBuilder(
      int index) {
    return tags_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    for (int i = 0; i < comments_.size(); i++) {
      output.writeMessage(4, comments_.get(i));
    }
    for (int i = 0; i < likes_.size(); i++) {
      output.writeMessage(5, likes_.get(i));
    }
    for (int i = 0; i < shares_.size(); i++) {
      output.writeMessage(6, shares_.get(i));
    }
    for (int i = 0; i < tags_.size(); i++) {
      output.writeMessage(7, tags_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    for (int i = 0; i < comments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, comments_.get(i));
    }
    for (int i = 0; i < likes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, likes_.get(i));
    }
    for (int i = 0; i < shares_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, shares_.get(i));
    }
    for (int i = 0; i < tags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, tags_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.service.grpc.newsfeed.Post)) {
      return super.equals(obj);
    }
    web.service.grpc.newsfeed.Post other = (web.service.grpc.newsfeed.Post) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getUserId()
        == other.getUserId());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getCommentsList()
        .equals(other.getCommentsList());
    result = result && getLikesList()
        .equals(other.getLikesList());
    result = result && getSharesList()
        .equals(other.getSharesList());
    result = result && getTagsList()
        .equals(other.getTagsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (getCommentsCount() > 0) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getCommentsList().hashCode();
    }
    if (getLikesCount() > 0) {
      hash = (37 * hash) + LIKES_FIELD_NUMBER;
      hash = (53 * hash) + getLikesList().hashCode();
    }
    if (getSharesCount() > 0) {
      hash = (37 * hash) + SHARES_FIELD_NUMBER;
      hash = (53 * hash) + getSharesList().hashCode();
    }
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.service.grpc.newsfeed.Post parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.newsfeed.Post parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.service.grpc.newsfeed.Post parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.grpc.newsfeed.Post parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.service.grpc.newsfeed.Post prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Post}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Post)
      web.service.grpc.newsfeed.PostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.grpc.newsfeed.Newsfeed.internal_static_Post_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.grpc.newsfeed.Newsfeed.internal_static_Post_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.grpc.newsfeed.Post.class, web.service.grpc.newsfeed.Post.Builder.class);
    }

    // Construct using web.service.grpc.newsfeed.Post.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommentsFieldBuilder();
        getLikesFieldBuilder();
        getSharesFieldBuilder();
        getTagsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      userId_ = 0L;

      content_ = "";

      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        commentsBuilder_.clear();
      }
      if (likesBuilder_ == null) {
        likes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        likesBuilder_.clear();
      }
      if (sharesBuilder_ == null) {
        shares_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        sharesBuilder_.clear();
      }
      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        tagsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.service.grpc.newsfeed.Newsfeed.internal_static_Post_descriptor;
    }

    public web.service.grpc.newsfeed.Post getDefaultInstanceForType() {
      return web.service.grpc.newsfeed.Post.getDefaultInstance();
    }

    public web.service.grpc.newsfeed.Post build() {
      web.service.grpc.newsfeed.Post result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public web.service.grpc.newsfeed.Post buildPartial() {
      web.service.grpc.newsfeed.Post result = new web.service.grpc.newsfeed.Post(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.userId_ = userId_;
      result.content_ = content_;
      if (commentsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          comments_ = java.util.Collections.unmodifiableList(comments_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.comments_ = comments_;
      } else {
        result.comments_ = commentsBuilder_.build();
      }
      if (likesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          likes_ = java.util.Collections.unmodifiableList(likes_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.likes_ = likes_;
      } else {
        result.likes_ = likesBuilder_.build();
      }
      if (sharesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          shares_ = java.util.Collections.unmodifiableList(shares_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.shares_ = shares_;
      } else {
        result.shares_ = sharesBuilder_.build();
      }
      if (tagsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.service.grpc.newsfeed.Post) {
        return mergeFrom((web.service.grpc.newsfeed.Post)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(web.service.grpc.newsfeed.Post other) {
      if (other == web.service.grpc.newsfeed.Post.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (commentsBuilder_ == null) {
        if (!other.comments_.isEmpty()) {
          if (comments_.isEmpty()) {
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCommentsIsMutable();
            comments_.addAll(other.comments_);
          }
          onChanged();
        }
      } else {
        if (!other.comments_.isEmpty()) {
          if (commentsBuilder_.isEmpty()) {
            commentsBuilder_.dispose();
            commentsBuilder_ = null;
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000008);
            commentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommentsFieldBuilder() : null;
          } else {
            commentsBuilder_.addAllMessages(other.comments_);
          }
        }
      }
      if (likesBuilder_ == null) {
        if (!other.likes_.isEmpty()) {
          if (likes_.isEmpty()) {
            likes_ = other.likes_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLikesIsMutable();
            likes_.addAll(other.likes_);
          }
          onChanged();
        }
      } else {
        if (!other.likes_.isEmpty()) {
          if (likesBuilder_.isEmpty()) {
            likesBuilder_.dispose();
            likesBuilder_ = null;
            likes_ = other.likes_;
            bitField0_ = (bitField0_ & ~0x00000010);
            likesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLikesFieldBuilder() : null;
          } else {
            likesBuilder_.addAllMessages(other.likes_);
          }
        }
      }
      if (sharesBuilder_ == null) {
        if (!other.shares_.isEmpty()) {
          if (shares_.isEmpty()) {
            shares_ = other.shares_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSharesIsMutable();
            shares_.addAll(other.shares_);
          }
          onChanged();
        }
      } else {
        if (!other.shares_.isEmpty()) {
          if (sharesBuilder_.isEmpty()) {
            sharesBuilder_.dispose();
            sharesBuilder_ = null;
            shares_ = other.shares_;
            bitField0_ = (bitField0_ & ~0x00000020);
            sharesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSharesFieldBuilder() : null;
          } else {
            sharesBuilder_.addAllMessages(other.shares_);
          }
        }
      }
      if (tagsBuilder_ == null) {
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
      } else {
        if (!other.tags_.isEmpty()) {
          if (tagsBuilder_.isEmpty()) {
            tagsBuilder_.dispose();
            tagsBuilder_ = null;
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000040);
            tagsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagsFieldBuilder() : null;
          } else {
            tagsBuilder_.addAllMessages(other.tags_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.service.grpc.newsfeed.Post parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.service.grpc.newsfeed.Post) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 2;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.util.List<web.service.grpc.newsfeed.Comment> comments_ =
      java.util.Collections.emptyList();
    private void ensureCommentsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        comments_ = new java.util.ArrayList<web.service.grpc.newsfeed.Comment>(comments_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Comment, web.service.grpc.newsfeed.Comment.Builder, web.service.grpc.newsfeed.CommentOrBuilder> commentsBuilder_;

    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Comment> getCommentsList() {
      if (commentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(comments_);
      } else {
        return commentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public int getCommentsCount() {
      if (commentsBuilder_ == null) {
        return comments_.size();
      } else {
        return commentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public web.service.grpc.newsfeed.Comment getComments(int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);
      } else {
        return commentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder setComments(
        int index, web.service.grpc.newsfeed.Comment value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.set(index, value);
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder setComments(
        int index, web.service.grpc.newsfeed.Comment.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.set(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder addComments(web.service.grpc.newsfeed.Comment value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder addComments(
        int index, web.service.grpc.newsfeed.Comment value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(index, value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder addComments(
        web.service.grpc.newsfeed.Comment.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder addComments(
        int index, web.service.grpc.newsfeed.Comment.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder addAllComments(
        java.lang.Iterable<? extends web.service.grpc.newsfeed.Comment> values) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, comments_);
        onChanged();
      } else {
        commentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder clearComments() {
      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        commentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public Builder removeComments(int index) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.remove(index);
        onChanged();
      } else {
        commentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public web.service.grpc.newsfeed.Comment.Builder getCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public web.service.grpc.newsfeed.CommentOrBuilder getCommentsOrBuilder(
        int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);  } else {
        return commentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public java.util.List<? extends web.service.grpc.newsfeed.CommentOrBuilder> 
         getCommentsOrBuilderList() {
      if (commentsBuilder_ != null) {
        return commentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(comments_);
      }
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public web.service.grpc.newsfeed.Comment.Builder addCommentsBuilder() {
      return getCommentsFieldBuilder().addBuilder(
          web.service.grpc.newsfeed.Comment.getDefaultInstance());
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public web.service.grpc.newsfeed.Comment.Builder addCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().addBuilder(
          index, web.service.grpc.newsfeed.Comment.getDefaultInstance());
    }
    /**
     * <code>repeated .Comment comments = 4;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Comment.Builder> 
         getCommentsBuilderList() {
      return getCommentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Comment, web.service.grpc.newsfeed.Comment.Builder, web.service.grpc.newsfeed.CommentOrBuilder> 
        getCommentsFieldBuilder() {
      if (commentsBuilder_ == null) {
        commentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.grpc.newsfeed.Comment, web.service.grpc.newsfeed.Comment.Builder, web.service.grpc.newsfeed.CommentOrBuilder>(
                comments_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        comments_ = null;
      }
      return commentsBuilder_;
    }

    private java.util.List<web.service.grpc.newsfeed.Like> likes_ =
      java.util.Collections.emptyList();
    private void ensureLikesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        likes_ = new java.util.ArrayList<web.service.grpc.newsfeed.Like>(likes_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Like, web.service.grpc.newsfeed.Like.Builder, web.service.grpc.newsfeed.LikeOrBuilder> likesBuilder_;

    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Like> getLikesList() {
      if (likesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(likes_);
      } else {
        return likesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public int getLikesCount() {
      if (likesBuilder_ == null) {
        return likes_.size();
      } else {
        return likesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public web.service.grpc.newsfeed.Like getLikes(int index) {
      if (likesBuilder_ == null) {
        return likes_.get(index);
      } else {
        return likesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder setLikes(
        int index, web.service.grpc.newsfeed.Like value) {
      if (likesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLikesIsMutable();
        likes_.set(index, value);
        onChanged();
      } else {
        likesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder setLikes(
        int index, web.service.grpc.newsfeed.Like.Builder builderForValue) {
      if (likesBuilder_ == null) {
        ensureLikesIsMutable();
        likes_.set(index, builderForValue.build());
        onChanged();
      } else {
        likesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder addLikes(web.service.grpc.newsfeed.Like value) {
      if (likesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLikesIsMutable();
        likes_.add(value);
        onChanged();
      } else {
        likesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder addLikes(
        int index, web.service.grpc.newsfeed.Like value) {
      if (likesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLikesIsMutable();
        likes_.add(index, value);
        onChanged();
      } else {
        likesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder addLikes(
        web.service.grpc.newsfeed.Like.Builder builderForValue) {
      if (likesBuilder_ == null) {
        ensureLikesIsMutable();
        likes_.add(builderForValue.build());
        onChanged();
      } else {
        likesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder addLikes(
        int index, web.service.grpc.newsfeed.Like.Builder builderForValue) {
      if (likesBuilder_ == null) {
        ensureLikesIsMutable();
        likes_.add(index, builderForValue.build());
        onChanged();
      } else {
        likesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder addAllLikes(
        java.lang.Iterable<? extends web.service.grpc.newsfeed.Like> values) {
      if (likesBuilder_ == null) {
        ensureLikesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, likes_);
        onChanged();
      } else {
        likesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder clearLikes() {
      if (likesBuilder_ == null) {
        likes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        likesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public Builder removeLikes(int index) {
      if (likesBuilder_ == null) {
        ensureLikesIsMutable();
        likes_.remove(index);
        onChanged();
      } else {
        likesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public web.service.grpc.newsfeed.Like.Builder getLikesBuilder(
        int index) {
      return getLikesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public web.service.grpc.newsfeed.LikeOrBuilder getLikesOrBuilder(
        int index) {
      if (likesBuilder_ == null) {
        return likes_.get(index);  } else {
        return likesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public java.util.List<? extends web.service.grpc.newsfeed.LikeOrBuilder> 
         getLikesOrBuilderList() {
      if (likesBuilder_ != null) {
        return likesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(likes_);
      }
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public web.service.grpc.newsfeed.Like.Builder addLikesBuilder() {
      return getLikesFieldBuilder().addBuilder(
          web.service.grpc.newsfeed.Like.getDefaultInstance());
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public web.service.grpc.newsfeed.Like.Builder addLikesBuilder(
        int index) {
      return getLikesFieldBuilder().addBuilder(
          index, web.service.grpc.newsfeed.Like.getDefaultInstance());
    }
    /**
     * <code>repeated .Like likes = 5;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Like.Builder> 
         getLikesBuilderList() {
      return getLikesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Like, web.service.grpc.newsfeed.Like.Builder, web.service.grpc.newsfeed.LikeOrBuilder> 
        getLikesFieldBuilder() {
      if (likesBuilder_ == null) {
        likesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.grpc.newsfeed.Like, web.service.grpc.newsfeed.Like.Builder, web.service.grpc.newsfeed.LikeOrBuilder>(
                likes_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        likes_ = null;
      }
      return likesBuilder_;
    }

    private java.util.List<web.service.grpc.newsfeed.Share> shares_ =
      java.util.Collections.emptyList();
    private void ensureSharesIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        shares_ = new java.util.ArrayList<web.service.grpc.newsfeed.Share>(shares_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Share, web.service.grpc.newsfeed.Share.Builder, web.service.grpc.newsfeed.ShareOrBuilder> sharesBuilder_;

    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Share> getSharesList() {
      if (sharesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(shares_);
      } else {
        return sharesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public int getSharesCount() {
      if (sharesBuilder_ == null) {
        return shares_.size();
      } else {
        return sharesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public web.service.grpc.newsfeed.Share getShares(int index) {
      if (sharesBuilder_ == null) {
        return shares_.get(index);
      } else {
        return sharesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder setShares(
        int index, web.service.grpc.newsfeed.Share value) {
      if (sharesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSharesIsMutable();
        shares_.set(index, value);
        onChanged();
      } else {
        sharesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder setShares(
        int index, web.service.grpc.newsfeed.Share.Builder builderForValue) {
      if (sharesBuilder_ == null) {
        ensureSharesIsMutable();
        shares_.set(index, builderForValue.build());
        onChanged();
      } else {
        sharesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder addShares(web.service.grpc.newsfeed.Share value) {
      if (sharesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSharesIsMutable();
        shares_.add(value);
        onChanged();
      } else {
        sharesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder addShares(
        int index, web.service.grpc.newsfeed.Share value) {
      if (sharesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSharesIsMutable();
        shares_.add(index, value);
        onChanged();
      } else {
        sharesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder addShares(
        web.service.grpc.newsfeed.Share.Builder builderForValue) {
      if (sharesBuilder_ == null) {
        ensureSharesIsMutable();
        shares_.add(builderForValue.build());
        onChanged();
      } else {
        sharesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder addShares(
        int index, web.service.grpc.newsfeed.Share.Builder builderForValue) {
      if (sharesBuilder_ == null) {
        ensureSharesIsMutable();
        shares_.add(index, builderForValue.build());
        onChanged();
      } else {
        sharesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder addAllShares(
        java.lang.Iterable<? extends web.service.grpc.newsfeed.Share> values) {
      if (sharesBuilder_ == null) {
        ensureSharesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shares_);
        onChanged();
      } else {
        sharesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder clearShares() {
      if (sharesBuilder_ == null) {
        shares_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        sharesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public Builder removeShares(int index) {
      if (sharesBuilder_ == null) {
        ensureSharesIsMutable();
        shares_.remove(index);
        onChanged();
      } else {
        sharesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public web.service.grpc.newsfeed.Share.Builder getSharesBuilder(
        int index) {
      return getSharesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public web.service.grpc.newsfeed.ShareOrBuilder getSharesOrBuilder(
        int index) {
      if (sharesBuilder_ == null) {
        return shares_.get(index);  } else {
        return sharesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public java.util.List<? extends web.service.grpc.newsfeed.ShareOrBuilder> 
         getSharesOrBuilderList() {
      if (sharesBuilder_ != null) {
        return sharesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(shares_);
      }
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public web.service.grpc.newsfeed.Share.Builder addSharesBuilder() {
      return getSharesFieldBuilder().addBuilder(
          web.service.grpc.newsfeed.Share.getDefaultInstance());
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public web.service.grpc.newsfeed.Share.Builder addSharesBuilder(
        int index) {
      return getSharesFieldBuilder().addBuilder(
          index, web.service.grpc.newsfeed.Share.getDefaultInstance());
    }
    /**
     * <code>repeated .Share shares = 6;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Share.Builder> 
         getSharesBuilderList() {
      return getSharesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Share, web.service.grpc.newsfeed.Share.Builder, web.service.grpc.newsfeed.ShareOrBuilder> 
        getSharesFieldBuilder() {
      if (sharesBuilder_ == null) {
        sharesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.grpc.newsfeed.Share, web.service.grpc.newsfeed.Share.Builder, web.service.grpc.newsfeed.ShareOrBuilder>(
                shares_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        shares_ = null;
      }
      return sharesBuilder_;
    }

    private java.util.List<web.service.grpc.newsfeed.Tag> tags_ =
      java.util.Collections.emptyList();
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        tags_ = new java.util.ArrayList<web.service.grpc.newsfeed.Tag>(tags_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Tag, web.service.grpc.newsfeed.Tag.Builder, web.service.grpc.newsfeed.TagOrBuilder> tagsBuilder_;

    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Tag> getTagsList() {
      if (tagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tags_);
      } else {
        return tagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public int getTagsCount() {
      if (tagsBuilder_ == null) {
        return tags_.size();
      } else {
        return tagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public web.service.grpc.newsfeed.Tag getTags(int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);
      } else {
        return tagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder setTags(
        int index, web.service.grpc.newsfeed.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder setTags(
        int index, web.service.grpc.newsfeed.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder addTags(web.service.grpc.newsfeed.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder addTags(
        int index, web.service.grpc.newsfeed.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(index, value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder addTags(
        web.service.grpc.newsfeed.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder addTags(
        int index, web.service.grpc.newsfeed.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder addAllTags(
        java.lang.Iterable<? extends web.service.grpc.newsfeed.Tag> values) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
      } else {
        tagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        tagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public Builder removeTags(int index) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.remove(index);
        onChanged();
      } else {
        tagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public web.service.grpc.newsfeed.Tag.Builder getTagsBuilder(
        int index) {
      return getTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public web.service.grpc.newsfeed.TagOrBuilder getTagsOrBuilder(
        int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);  } else {
        return tagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public java.util.List<? extends web.service.grpc.newsfeed.TagOrBuilder> 
         getTagsOrBuilderList() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tags_);
      }
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public web.service.grpc.newsfeed.Tag.Builder addTagsBuilder() {
      return getTagsFieldBuilder().addBuilder(
          web.service.grpc.newsfeed.Tag.getDefaultInstance());
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public web.service.grpc.newsfeed.Tag.Builder addTagsBuilder(
        int index) {
      return getTagsFieldBuilder().addBuilder(
          index, web.service.grpc.newsfeed.Tag.getDefaultInstance());
    }
    /**
     * <code>repeated .Tag tags = 7;</code>
     */
    public java.util.List<web.service.grpc.newsfeed.Tag.Builder> 
         getTagsBuilderList() {
      return getTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.grpc.newsfeed.Tag, web.service.grpc.newsfeed.Tag.Builder, web.service.grpc.newsfeed.TagOrBuilder> 
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.grpc.newsfeed.Tag, web.service.grpc.newsfeed.Tag.Builder, web.service.grpc.newsfeed.TagOrBuilder>(
                tags_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Post)
  }

  // @@protoc_insertion_point(class_scope:Post)
  private static final web.service.grpc.newsfeed.Post DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.service.grpc.newsfeed.Post();
  }

  public static web.service.grpc.newsfeed.Post getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Post>
      PARSER = new com.google.protobuf.AbstractParser<Post>() {
    public Post parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Post(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Post> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Post> getParserForType() {
    return PARSER;
  }

  public web.service.grpc.newsfeed.Post getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

